const SEED_DATA: Array<{ brand: string; model: string }> = [
  { brand: 'Airman', model: '55' },
  { brand: 'Airman', model: 'AX27' },
  { brand: 'Airman', model: 'AX33' },
  { brand: 'Airman', model: 'AX50' },
  { brand: 'Ammann', model: 'AMX100' },
  { brand: 'Ammann', model: 'AMX85' },
  { brand: 'Atlas', model: '140' },
  { brand: 'Atlas', model: '150' },
  { brand: 'Atlas', model: '160' },
  { brand: 'Atlas', model: '160 special NL' },
  { brand: 'Atlas', model: '1604ZW' },
  { brand: 'Atlas', model: '1605' },
  { brand: 'Bobcat', model: '334' },
  { brand: 'Bobcat', model: 'E08' },
  { brand: 'Bobcat', model: 'E10' },
  { brand: 'Bobcat', model: 'E14/E17' },
  { brand: 'Bobcat', model: 'E145' },
  { brand: 'Bobcat', model: 'E16/E19' },
  { brand: 'Bobcat', model: 'E165' },
  { brand: 'Bobcat', model: 'E20' },
  { brand: 'Bobcat', model: 'E25/E27' },
  { brand: 'Bobcat', model: 'E26' },
  { brand: 'Bobcat', model: 'E32/E35' },
  { brand: 'Bobcat', model: 'E42 R2' },
  { brand: 'Bobcat', model: 'E45/E55' },
  { brand: 'Bobcat', model: 'E50' },
  { brand: 'Bobcat', model: 'E57 Cast' },
  { brand: 'Bobcat', model: 'E60 R2' },
  { brand: 'Bobcat', model: 'E62' },
  { brand: 'Bobcat', model: 'E80/85' },
  { brand: 'Bobcat', model: 'E85R' },
  { brand: 'Bobcat', model: 'E88 R2' },
  { brand: 'Bobcat', model: 'E88R' },
  { brand: 'Brokk', model: '520D' },
  { brand: 'Carter', model: 'CT16' },
  { brand: 'Carter', model: 'CT18' },
  { brand: 'Carter', model: 'CT26' },
  { brand: 'Carter', model: 'CT27' },
  { brand: 'Case', model: '210/240' },
  { brand: 'Case', model: '695ST' },
  { brand: 'Case', model: 'CX12D' },
  { brand: 'Case', model: 'CX15EV' },
  { brand: 'Case', model: 'CX19D' },
  { brand: 'Case', model: 'CX25EV' },
  { brand: 'Case', model: 'CX30D' },
  { brand: 'Case', model: 'CX35D' },
  { brand: 'Case', model: 'CX37D' },
  { brand: 'Case', model: 'CX42D' },
  { brand: 'Case', model: 'CX50D' },
  { brand: 'Case', model: 'CX60D' },
  { brand: 'Case', model: 'CX70E' },
  { brand: 'Case', model: 'CX85E' },
  { brand: 'Case', model: 'CX90E' },
  { brand: 'Case', model: 'CX100E' },
  { brand: 'Case', model: 'CX130D' },
  { brand: 'Case', model: 'CX130E' },
  { brand: 'Case', model: 'CX140SR' },
  { brand: 'Case', model: 'CX145D SR (Also w offset boom)' },
  { brand: 'Case', model: 'CX160D' },
  { brand: 'Case', model: 'CX160E' },
  { brand: 'Case', model: 'CX16B' },
  { brand: 'Case', model: 'CX180D/E' },
  { brand: 'Case', model: 'CX18B' },
  { brand: 'Case', model: 'CX210D' },
  { brand: 'Case', model: 'CX210E' },
  { brand: 'Case', model: 'CX240D' },
  { brand: 'Case', model: 'CX240E' },
  { brand: 'Case', model: 'CX245D SR' },
  { brand: 'Case', model: 'CX250D' },
  { brand: 'Case', model: 'CX250D/E LR' },
  { brand: 'Case', model: 'CX250E' },
  { brand: 'Case', model: 'CX250LC' },
  { brand: 'Case', model: 'CX28' },
  { brand: 'Case', model: 'CX28D' },
  { brand: 'Case', model: 'CX290D/E MH' },
  { brand: 'Case', model: 'CX300D' },
  { brand: 'Case', model: 'CX300E' },
  { brand: 'Case', model: 'CX31B/35B/36B/39B' },
  { brand: 'Case', model: 'CX350D/E' },
  { brand: 'Case', model: 'CX36' },
  { brand: 'Case', model: 'CX365E SR' },
  { brand: 'Case', model: 'CX370D/E' },
  { brand: 'Case', model: 'CX40B' },
  { brand: 'Case', model: 'CX460' },
  { brand: 'Case', model: 'CX490' },
  { brand: 'Case', model: 'CX490D/E' },
  { brand: 'Case', model: 'CX500D/E ME' },
  { brand: 'Case', model: 'CX50B' },
  { brand: 'Case', model: 'CX57' },
  { brand: 'Case', model: 'CX60C' },
  { brand: 'Case', model: 'CX75' },
  { brand: 'Case', model: 'CX80' },
  { brand: 'Case', model: 'CX90' },
  { brand: 'Case', model: 'CX750D/E ME' },
  { brand: 'Case', model: 'CX75C SR' },
  { brand: 'Case', model: 'CX85D/E SR (also offset boom)' },
  { brand: 'Case', model: 'CX90D' },
  { brand: 'Case', model: 'CX90E' },
  { brand: 'Case', model: 'WX140E' },
  { brand: 'Case', model: 'WX148' },
  { brand: 'Case', model: 'WX155E SR' },
  { brand: 'Case', model: 'WX160E' },
  { brand: 'Case', model: 'WX168' },
  { brand: 'Case', model: 'WX175E SR' },
  { brand: 'Case', model: 'WX210E' },
  { brand: 'Case', model: 'WX218' },
  { brand: 'CAT', model: '301.4C' },
  { brand: 'CAT', model: '301.5' },
  { brand: 'CAT', model: '301.5 NG' },
  { brand: 'CAT', model: '301.6C' },
  { brand: 'CAT', model: '301.7 CR NG' },
  { brand: 'CAT', model: '301.7D' },
  { brand: 'CAT', model: '301.7DCR' },
  { brand: 'CAT', model: '301.8' },
  { brand: 'CAT', model: '301.8 NG' },
  { brand: 'CAT', model: '301.8C' },
  { brand: 'CAT', model: '302 CR NG' },
  { brand: 'CAT', model: '302.2D' },
  { brand: 'CAT', model: '302.4D' },
  { brand: 'CAT', model: '302.5' },
  { brand: 'CAT', model: '302.5C' },
  { brand: 'CAT', model: '302.7 CR NG' },
  { brand: 'CAT', model: '302.7D' },
  { brand: 'CAT', model: '303 CR NG' },
  { brand: 'CAT', model: '303.5' },
  { brand: 'CAT', model: '303.5 CR NG' },
  { brand: 'CAT', model: '303.5-03' },
  { brand: 'CAT', model: '303.5C-CR' },
  { brand: 'CAT', model: '303.5D-CR' },
  { brand: 'CAT', model: '303.5E-CR' },
  { brand: 'CAT', model: '303.5E2' },
  { brand: 'CAT', model: '303C-CR' },
  { brand: 'CAT', model: '303E-CR' },
  { brand: 'CAT', model: '304 NG' },
  { brand: 'CAT', model: '304.5' },
  { brand: 'CAT', model: '304.5E2' },
  { brand: 'CAT', model: '304C CR' },
  { brand: 'CAT', model: '304C/305C' },
  { brand: 'CAT', model: '304CR' },
  { brand: 'CAT', model: '304D CR' },
  { brand: 'CAT', model: '304E CR' },
  { brand: 'CAT', model: '304E2' },
  { brand: 'CAT', model: '305 CR NG' },
  { brand: 'CAT', model: '305 E2' },
  { brand: 'CAT', model: '305.5 E CR' },
  { brand: 'CAT', model: '305.5D CR' },
  { brand: 'CAT', model: '305CR' },
  { brand: 'CAT', model: '305D CR' },
  { brand: 'CAT', model: '305E' },
  { brand: 'CAT', model: '305E CR' },
  { brand: 'CAT', model: '306 CR NG' },
  { brand: 'CAT', model: '306 E2' },
  { brand: 'CAT', model: '307.5 NG' },
  { brand: 'CAT', model: '308 CR NG' },
  { brand: 'CAT', model: '309 CR NG' },
  { brand: 'CAT', model: '30C CR' },
  { brand: 'CAT', model: '310 NG' },
  { brand: 'CAT', model: '311C' },
  { brand: 'CAT', model: '311F/314E' },
  { brand: 'CAT', model: '312D/E' },
  { brand: 'CAT', model: '313 GC NG' },
  { brand: 'CAT', model: '313 NG' },
  { brand: 'CAT', model: '313F GC / 313F' },
  { brand: 'CAT', model: '314C' },
  { brand: 'CAT', model: '314D' },
  { brand: 'CAT', model: '314F' },
  { brand: 'CAT', model: '315 GC NG' },
  { brand: 'CAT', model: '315 NG' },
  { brand: 'CAT', model: '315CL' },
  { brand: 'CAT', model: '315D' },
  { brand: 'CAT', model: '315F' },
  { brand: 'CAT', model: '316F' },
  { brand: 'CAT', model: '317 GC NG' },
  { brand: 'CAT', model: '317 NG' },
  { brand: 'CAT', model: '318F' },
  { brand: 'CAT', model: '319D' },
  { brand: 'CAT', model: '320 GC NG' },
  { brand: 'CAT', model: '320 NG' },
  { brand: 'CAT', model: '320D' },
  { brand: 'CAT', model: '320F/323F/320E' },
  { brand: 'CAT', model: '323 NG' },
  { brand: 'CAT', model: '323D' },
  { brand: 'CAT', model: '324D/324E' },
  { brand: 'CAT', model: '325 NG' },
  { brand: 'CAT', model: '325C' },
  { brand: 'CAT', model: '325D' },
  { brand: 'CAT', model: '325F' },
  { brand: 'CAT', model: '326 NG' },
  { brand: 'CAT', model: '326D2' },
  { brand: 'CAT', model: '326F' },
  { brand: 'CAT', model: '326FL' },
  { brand: 'CAT', model: '328' },
  { brand: 'CAT', model: '329D/329D2/329E/329F' },
  { brand: 'CAT', model: '330 GC NG' },
  { brand: 'CAT', model: '330 NG' },
  { brand: 'CAT', model: '330D' },
  { brand: 'CAT', model: '330D2' },
  { brand: 'CAT', model: '330F' },
  { brand: 'CAT', model: '335 NG' },
  { brand: 'CAT', model: '335F' },
  { brand: 'CAT', model: '335F CR' },
  { brand: 'CAT', model: '336' },
  { brand: 'CAT', model: '336 NG' },
  { brand: 'CAT', model: '340 NG' },
  { brand: 'CAT', model: '374 Reach' },
  { brand: 'CAT', model: '374 MASS' },
  { brand: 'CAT', model: 'M312' },
  { brand: 'CAT', model: 'M313C/M313D' },
  { brand: 'CAT', model: 'M314 NG' },
  { brand: 'CAT', model: 'M314F' },
  { brand: 'CAT', model: 'M315 NG' },
  { brand: 'CAT', model: 'M315C/M315D/M315F' },
  { brand: 'CAT', model: 'M316 NG' },
  { brand: 'CAT', model: 'M316C/M316D/M316F' },
  { brand: 'CAT', model: 'M318 NG' },
  { brand: 'CAT', model: 'M318C/M318D' },
  { brand: 'CAT', model: 'M318F' },
  { brand: 'CAT', model: 'M319 NG' },
  { brand: 'CAT', model: 'M320 NG' },
  { brand: 'CAT', model: 'M322 NG' },
  { brand: 'CAT', model: 'M322C/D/F' },
  { brand: 'CAT', model: 'M325D MH' },
  { brand: 'Colmar', model: 'T10000FCS' },
  { brand: 'Coltrax', model: 'CX10' },
  { brand: 'Coltrax', model: 'CX15' },
  { brand: 'Coltrax', model: 'CX22/CX25' },
  { brand: 'Coltrax', model: 'CX35' },
  { brand: 'Coltrax', model: 'CX40' },
  { brand: 'Coltrax', model: 'CX50/CX57/CX60' },
  { brand: 'Coltrax', model: 'CX85S/CX85C/CX90CD/CX95ST' },
  { brand: 'Doosan', model: 'DX10/DX19' },
  { brand: 'Doosan', model: 'DX100W-7' },
  { brand: 'Doosan', model: 'DX140 W/LC-3/-5/-7' },
  { brand: 'Doosan', model: 'DX140W Korea' },
  { brand: 'Doosan', model: 'DX160 W/LC-5' },
  { brand: 'Doosan', model: 'DX165W-5' },
  { brand: 'Doosan', model: 'DX170LC-7' },
  { brand: 'Doosan', model: 'DX170W' },
  { brand: 'Doosan', model: 'DX170W-5' },
  { brand: 'Doosan', model: 'DX180LC-3/-5' },
  { brand: 'Doosan', model: 'DX190W-7' },
  { brand: 'Doosan', model: 'DX200LC-7' },
  { brand: 'Doosan', model: 'DX210W-7' },
  { brand: 'Doosan', model: 'DX210W/DX210LC' },
  { brand: 'Doosan', model: 'DX220LC/DX220LCR' },
  { brand: 'Doosan', model: 'DX225LC-7' },
  { brand: 'Doosan', model: 'DX235' },
  { brand: 'Doosan', model: 'DX235LCR-7' },
  { brand: 'Doosan', model: 'DX250LC' },
  { brand: 'Doosan', model: 'DX255LC-3/-5/-7' },
  { brand: 'Doosan', model: 'DX27Z-7' },
  { brand: 'Doosan', model: 'DX300LC-7 SLR' },
  { brand: 'Doosan', model: 'DX300LC-3' },
  { brand: 'Doosan', model: 'DX300LC-5' },
  { brand: 'Doosan', model: 'DX300LC-7' },
  { brand: 'Doosan', model: 'DX30Z/35Z' },
  { brand: 'Doosan', model: 'DX340LC/-3/-5' },
  { brand: 'Doosan', model: 'DX350LC-7' },
  { brand: 'Doosan', model: 'DX35Z-7' },
  { brand: 'Doosan', model: 'DX360LCR-7' },
  { brand: 'Doosan', model: 'DX380LC' },
  { brand: 'Doosan', model: 'DX42-7' },
  { brand: 'Doosan', model: 'DX420LC-7' },
  { brand: 'Doosan', model: 'DX480' },
  { brand: 'Doosan', model: 'DX490LC-7' },
  { brand: 'Doosan', model: 'DX50Z-7' },
  { brand: 'Doosan', model: 'DX520' },
  { brand: 'Doosan', model: 'DX530LC-7' },
  { brand: 'Doosan', model: 'DX530LC-7 SLR' },
  { brand: 'Doosan', model: 'DX55' },
  { brand: 'Doosan', model: 'DX55W' },
  { brand: 'Doosan', model: 'DX55MT' },
  { brand: 'Doosan', model: 'DX55E' },
  { brand: 'Doosan', model: 'DX57' },
  { brand: 'Doosan', model: 'DX60R' },
  { brand: 'Doosan', model: 'DX62R-3' },
  { brand: 'Doosan', model: 'DX63-7' },
  { brand: 'Doosan', model: 'DX80' },
  { brand: 'Doosan', model: 'DX85R-3' },
  { brand: 'Doosan', model: 'DX89R-7' },
  { brand: 'Doosan', model: 'E60' },
  { brand: 'Doosan', model: 'E62' },
  { brand: 'Doosan', model: 'E80' },
  { brand: 'Doosan', model: 'E85' },
  { brand: 'Doosan', model: 'S010' },
  { brand: 'Doosan', model: 'S015' },
  { brand: 'Doosan', model: 'S018' },
  { brand: 'Doosan', model: 'S030' },
  { brand: 'Doosan', model: 'S035' },
  { brand: 'Doosan', model: 'S130LC' },
  { brand: 'Doosan', model: 'S140W-V/S140R-V/S140LC' },
  { brand: 'Doosan', model: 'S150LC' },
  { brand: 'Doosan', model: 'S155LC' },
  { brand: 'Doosan', model: 'S160W-V' },
  { brand: 'Doosan', model: 'S175LC-V' },
  { brand: 'Doosan', model: 'S180W-V' },
  { brand: 'Doosan', model: 'S210W-V' },
  { brand: 'Doosan', model: 'S225SLR' },
  { brand: 'Doosan', model: 'S255LC-V' },
  { brand: 'Doosan', model: 'S255SLR' },
  { brand: 'Doosan', model: 'S300DEM' },
  { brand: 'Doosan', model: 'S300LC-V' },
  { brand: 'Doosan', model: 'S300SLR' },
  { brand: 'Doosan', model: 'S340LC-V' },
  { brand: 'Doosan', model: 'S380LC-V' },
  { brand: 'Doosan', model: 'S420LC' },
  { brand: 'Doosan', model: 'S470LC' },
  { brand: 'Doosan', model: 'S55' },
  { brand: 'Doosan', model: 'S75-V' },
  { brand: 'Eurocomach', model: '15ZT - 17SR' },
  { brand: 'Eurocomach', model: '18ZT - 19ZT' },
  { brand: 'Eurocomach', model: '19TR' },
  { brand: 'Eurocomach', model: '45TR' },
  { brand: 'Eurocomach', model: 'ES100TR' },
  { brand: 'Eurocomach', model: 'ES10ZT' },
  { brand: 'Eurocomach', model: 'ES15SR' },
  { brand: 'Eurocomach', model: 'ES18ZT' },
  { brand: 'Eurocomach', model: 'ES22SR' },
  { brand: 'Eurocomach', model: 'ES25ZT' },
  { brand: 'Eurocomach', model: 'ES28ZT' },
  { brand: 'Eurocomach', model: 'ES300/300SR' },
  { brand: 'Eurocomach', model: 'ES350ZT' },
  { brand: 'Eurocomach', model: 'ES35ZT' },
  { brand: 'Eurocomach', model: 'ES400/400ZT' },
  { brand: 'Eurocomach', model: 'ES40ZT' },
  { brand: 'Eurocomach', model: 'ES50ZT/ES57ZT/ES60TR' },
  { brand: 'Eurocomach', model: 'ES850SB' },
  { brand: 'Eurocomach', model: 'ES850ZT' },
  { brand: 'Eurocomach', model: 'ES85SB' },
  { brand: 'Eurocomach', model: 'ES85ZT' },
  { brand: 'Eurocomach', model: 'ES900UR' },
  { brand: 'Eurocomach', model: 'ES90UR' },
  { brand: 'Eurocomach', model: 'ES90ZT' },
  { brand: 'Eurocomach', model: 'ES950TR' },
  { brand: 'Eurocomach', model: 'ES95TR' },
  { brand: 'Eurocomach', model: 'EZ12' },
  { brand: 'Eurocomach', model: 'R955' },
  { brand: 'Furukawa', model: 'CX145D SR' },
  { brand: 'Hanix', model: 'H28' },
  { brand: 'Hanix', model: 'H50/H55DR' },
  { brand: 'Hanix', model: 'N60/H65' },
  { brand: 'Hidromek', model: '200W/220LC/230W' },
  { brand: 'Hidromek', model: '300LC' },
  { brand: 'Hidromek', model: 'HMK102s G2' },
  { brand: 'Hidromek', model: 'HMK65ZT/70W' },
  { brand: 'Hidromek', model: 'K140W' },
  { brand: 'Hidromek', model: 'MH200W' },
  { brand: 'Hitachi', model: 'EX120' },
  { brand: 'Hitachi', model: 'EX130' },
  { brand: 'Hitachi', model: 'EX135' },
  { brand: 'Hitachi', model: 'EX400' },
  { brand: 'Hitachi', model: 'Zaxis 60 / ZX60USB-3/65USB-5' },
  { brand: 'Hitachi', model: 'ZX130-7H' },
  { brand: 'Hitachi', model: 'ZX130LCN-5/130W' },
  { brand: 'Hitachi', model: 'ZX135 Japan' },
  { brand: 'Hitachi', model: 'ZX135 US-7H' },
  { brand: 'Hitachi', model: 'ZX135US-3/-5/-6' },
  { brand: 'Hitachi', model: 'ZX140W' },
  { brand: 'Hitachi', model: 'Zx145WT' },
  { brand: 'Hitachi', model: 'ZX160LC-7H' },
  { brand: 'Hitachi', model: 'ZX160W -3/-6' },
  { brand: 'Hitachi', model: 'ZX170W -3/-6/-5' },
  { brand: 'Hitachi', model: 'ZX175W-7' },
  { brand: 'Hitachi', model: 'ZX17U-5N' },
  { brand: 'Hitachi', model: 'ZX18-3' },
  { brand: 'Hitachi', model: 'ZX180LC-3' },
  { brand: 'Hitachi', model: 'ZX180W-7' },
  { brand: 'Hitachi', model: 'ZX190LC-6' },
  { brand: 'Hitachi', model: 'ZX190LC-7H' },
  { brand: 'Hitachi', model: 'ZX190W' },
  { brand: 'Hitachi', model: 'ZX200X-6' },
  { brand: 'Hitachi', model: 'ZX210' },
  { brand: 'Hitachi', model: 'ZX210LC-H7' },
  { brand: 'Hitachi', model: 'ZX22' },
  { brand: 'Hitachi', model: 'ZX225US-3/USR-3' },
  { brand: 'Hitachi', model: 'ZX240' },
  { brand: 'Hitachi', model: 'ZX245USLC-7H' },
  { brand: 'Hitachi', model: 'ZX250-3' },
  { brand: 'Hitachi', model: 'ZX250-5' },
  { brand: 'Hitachi', model: 'ZX250-6' },
  { brand: 'Hitachi', model: 'ZX250LC-3' },
  { brand: 'Hitachi', model: 'ZX250LC-5B' },
  { brand: 'Hitachi', model: 'ZX250LC-6' },
  { brand: 'Hitachi', model: 'ZX250LC-7H' },
  { brand: 'Hitachi', model: 'ZX26-5' },
  { brand: 'Hitachi', model: 'ZX26U-5N' },
  { brand: 'Hitachi', model: 'ZX27' },
  { brand: 'Hitachi', model: 'ZX270' },
  { brand: 'Hitachi', model: 'ZX280' },
  { brand: 'Hitachi', model: 'ZX280-3' },
  { brand: 'Hitachi', model: 'ZX28U' },
  { brand: 'Hitachi', model: 'ZX290-5' },
  { brand: 'Hitachi', model: 'ZX30' },
  { brand: 'Hitachi', model: 'ZX30/35/40' },
  { brand: 'Hitachi', model: 'ZX300-6' },
  { brand: 'Hitachi', model: 'ZX300LC-5B' },
  { brand: 'Hitachi', model: 'ZX300LC-6' },
  { brand: 'Hitachi', model: 'ZX300LC-H7' },
  { brand: 'Hitachi', model: 'ZX30U-2' },
  { brand: 'Hitachi', model: 'ZX30U-5N' },
  { brand: 'Hitachi', model: 'ZX330' },
  { brand: 'Hitachi', model: 'ZX33U-3' },
  { brand: 'Hitachi', model: 'ZX33U-5' },
  { brand: 'Hitachi', model: 'ZX345USLC-7H' },
  { brand: 'Hitachi', model: 'ZX350-3' },
  { brand: 'Hitachi', model: 'ZX350-5' },
  { brand: 'Hitachi', model: 'ZX350-6' },
  { brand: 'Hitachi', model: 'ZX350-LC-7H' },
  { brand: 'Hitachi', model: 'ZX350-LC6' },
  { brand: 'Hitachi', model: 'ZX350-LC7' },
  { brand: 'Hitachi', model: 'ZX35U-2' },
  { brand: 'Hitachi', model: 'ZX35U-5N' },
  { brand: 'Hitachi', model: 'ZX360' },
  { brand: 'Hitachi', model: 'ZX380' },
  { brand: 'Hitachi', model: 'ZX38U-3' },
  { brand: 'Hitachi', model: 'ZX38U-5' },
  { brand: 'Hitachi', model: 'ZX40U-2' },
  { brand: 'Hitachi', model: 'ZX470' },
  { brand: 'Hitachi', model: 'ZX48U-3' },
  { brand: 'Hitachi', model: 'ZX48U-5' },
  { brand: 'Hitachi', model: 'ZX490' },
  { brand: 'Hitachi', model: 'ZX490LC-7H' },
  { brand: 'Hitachi', model: 'ZX50' },
  { brand: 'Hitachi', model: 'ZX50U-5' },
  { brand: 'Hitachi', model: 'ZX50U-5N' },
  { brand: 'Hitachi', model: 'ZX52U-3' },
  { brand: 'Hitachi', model: 'ZX530' },
  { brand: 'Hitachi', model: 'ZX55' },
  { brand: 'Hitachi', model: 'ZX55U-5' },
  { brand: 'Hitachi', model: 'ZX60USB-5N' },
  { brand: 'Hitachi', model: 'ZX690LC-7H' },
  { brand: 'Hitachi', model: 'ZX70' },
  { brand: 'Hitachi', model: 'ZX80' },
  { brand: 'Hitachi', model: 'ZX85' },
  { brand: 'Hitachi', model: 'ZX870' },
  { brand: 'Hitachi', model: 'ZX890 LC-7H' },
  { brand: 'Hitec', model: '-' },
  { brand: 'Huddig', model: '1260' },
  { brand: 'Hydrema', model: 'MX17' },
  { brand: 'Hyundai', model: 'HW100A' },
  { brand: 'Hyundai', model: 'HW140' },
  { brand: 'Hyundai', model: 'HW145' },
  { brand: 'Hyundai', model: 'HW160' },
  { brand: 'Hyundai', model: 'HW210' },
  { brand: 'Hyundai', model: 'HX140L' },
  { brand: 'Hyundai', model: 'HX140W' },
  { brand: 'Hyundai', model: 'HX145LCR' },
  { brand: 'Hyundai', model: 'HX160L' },
  { brand: 'Hyundai', model: 'HX17A' },
  { brand: 'Hyundai', model: 'HX19A' },
  { brand: 'Hyundai', model: 'HX17E' },
  { brand: 'Hyundai', model: 'HX25/30AZ' },
  { brand: 'Hyundai', model: 'HX35A Z' },
  { brand: 'Hyundai', model: 'HX40A' },
  { brand: 'Hyundai', model: 'HX180' },
  { brand: 'Hyundai', model: 'HX220 L' },
  { brand: 'Hyundai', model: 'HX235LCR' },
  { brand: 'Hyundai', model: 'HX260 L' },
  { brand: 'Hyundai', model: 'HX300 L' },
  { brand: 'Hyundai', model: 'HX330 L' },
  { brand: 'Hyundai', model: 'HX360L' },
  { brand: 'Hyundai', model: 'HX400L' },
  { brand: 'Hyundai', model: 'HX85' },
  { brand: 'Hyundai', model: 'LHW180' },
  { brand: 'Hyundai', model: 'R110-7' },
  { brand: 'Hyundai', model: 'R125LCR-9A' },
  { brand: 'Hyundai', model: 'R140' },
  { brand: 'Hyundai', model: 'R145' },
  { brand: 'Hyundai', model: 'R16-9' },
  { brand: 'Hyundai', model: 'R18-9' },
  { brand: 'Hyundai', model: 'R18-9AK' },
  { brand: 'Hyundai', model: 'R160LC-9 9S' },
  { brand: 'Hyundai', model: 'R160W-9A' },
  { brand: 'Hyundai', model: 'R170W-7/7A' },
  { brand: 'Hyundai', model: 'R170W-9 9S' },
  { brand: 'Hyundai', model: 'R17Z-9A' },
  { brand: 'Hyundai', model: 'R180LC-7' },
  { brand: 'Hyundai', model: 'R180LC-9 9S' },
  { brand: 'Hyundai', model: 'R200W-7' },
  { brand: 'Hyundai', model: 'R200W-7A' },
  { brand: 'Hyundai', model: 'R210-9' },
  { brand: 'Hyundai', model: 'R210LC-7' },
  { brand: 'Hyundai', model: 'R210LC-7A' },
  { brand: 'Hyundai', model: 'R210LC-9' },
  { brand: 'Hyundai', model: 'R210NLC-7' },
  { brand: 'Hyundai', model: 'R210NLC-7A' },
  { brand: 'Hyundai', model: 'R210W-9' },
  { brand: 'Hyundai', model: 'R220LC-9' },
  { brand: 'Hyundai', model: 'R235LCR-9' },
  { brand: 'Hyundai', model: 'R250LC-7/7A' },
  { brand: 'Hyundai', model: 'R250LC-9' },
  { brand: 'Hyundai', model: 'R25Z-9A (K)' },
  { brand: 'Hyundai', model: 'R260LC-9A' },
  { brand: 'Hyundai', model: 'R260LC-9S' },
  { brand: 'Hyundai', model: 'R27Z-9 (AK)' },
  { brand: 'Hyundai', model: 'R290LC-7/7A' },
  { brand: 'Hyundai', model: 'R290LC-9' },
  { brand: 'Hyundai', model: 'R300LC-9A' },
  { brand: 'Hyundai', model: 'R300LC-9S/9SH' },
  { brand: 'Hyundai', model: 'R305LC-7' },
  { brand: 'Hyundai', model: 'R30Z-9AK' },
  { brand: 'Hyundai', model: 'R320LC-7/7A' },
  { brand: 'Hyundai', model: 'R320LC-9' },
  { brand: 'Hyundai', model: 'R330LC-9A' },
  { brand: 'Hyundai', model: 'R330LC-9S/9SH' },
  { brand: 'Hyundai', model: 'R35-9' },
  { brand: 'Hyundai', model: 'R35Z-9 (A)' },
  { brand: 'Hyundai', model: 'R360LC-7/7A' },
  { brand: 'Hyundai', model: 'R380LC-9/9SH' },
  { brand: 'Hyundai', model: 'R380LC-9A' },
  { brand: 'Hyundai', model: 'R55-7/7A' },
  { brand: 'Hyundai', model: 'R55-9' },
  { brand: 'Hyundai', model: 'R55W-7/7A' },
  { brand: 'Hyundai', model: 'R55W-9' },
  { brand: 'Hyundai', model: 'R60-9S' },
  { brand: 'Hyundai', model: 'R60CR-9' },
  { brand: 'Hyundai', model: 'R60W-9S' },
  { brand: 'Hyundai', model: 'HX60' },
  { brand: 'Hyundai', model: 'HW60' },
  { brand: 'Hyundai', model: 'HX65A' },
  { brand: 'Hyundai', model: 'HW65AH' },
  { brand: 'Hyundai', model: 'R80-7/7A' },
  { brand: 'Hyundai', model: 'R80CR-9' },
  { brand: 'Hyundai', model: 'RC430LC-9/9SH' },
  { brand: 'IHI', model: '25VX' },
  { brand: 'IHI', model: '35N' },
  { brand: 'JCB', model: '100C-2' },
  { brand: 'JCB', model: '131X' },
  { brand: 'JCB', model: '145W G2' },
  { brand: 'JCB', model: '15' },
  { brand: 'JCB', model: '150X' },
  { brand: 'JCB', model: '16' },
  { brand: 'JCB', model: '18' },
  { brand: 'JCB', model: '19' },
  { brand: 'JCB', model: '1CX' },
  { brand: 'JCB', model: '220X' },
  { brand: 'JCB', model: '245XR' },
  { brand: 'JCB', model: '25Z' },
  { brand: 'JCB', model: '2CX' },
  { brand: 'JCB', model: '2DX' },
  { brand: 'JCB', model: '35Z-1' },
  { brand: 'JCB', model: '36C-1' },
  { brand: 'JCB', model: '370X' },
  { brand: 'JCB', model: '3CX' },
  { brand: 'JCB', model: '3CX 12L4WS (Compact)' },
  { brand: 'JCB', model: '3CX 14HFWA (Normal)' },
  { brand: 'JCB', model: '45Z' },
  { brand: 'JCB', model: '48Z' },
  { brand: 'JCB', model: '4CX' },
  { brand: 'JCB', model: '50Z' },
  { brand: 'JCB', model: '50Z-2' },
  { brand: 'JCB', model: '51R' },
  { brand: 'JCB', model: '55Z' },
  { brand: 'JCB', model: '56Z-2' },
  { brand: 'JCB', model: '57C' },
  { brand: 'JCB', model: '5CX' },
  { brand: 'JCB', model: '60C-2' },
  { brand: 'JCB', model: '67C-1' },
  { brand: 'JCB', model: '801' },
  { brand: 'JCB', model: '8018' },
  { brand: 'JCB', model: '802' },
  { brand: 'JCB', model: '8020' },
  { brand: 'JCB', model: '8025' },
  { brand: 'JCB', model: '8026' },
  { brand: 'JCB', model: '8027' },
  { brand: 'JCB', model: '8029' },
  { brand: 'JCB', model: '8030' },
  { brand: 'JCB', model: '8032' },
  { brand: 'JCB', model: '8035' },
  { brand: 'JCB', model: '8040' },
  { brand: 'JCB', model: '8045' },
  { brand: 'JCB', model: '8052' },
  { brand: 'JCB', model: '8055' },
  { brand: 'JCB', model: '8060' },
  { brand: 'JCB', model: '8065' },
  { brand: 'JCB', model: '8066' },
  { brand: 'JCB', model: '8080' },
  { brand: 'JCB', model: '8085' },
  { brand: 'JCB', model: '8086' },
  { brand: 'JCB', model: '85Z-1' },
  { brand: 'JCB', model: '86C' },
  { brand: 'JCB', model: '86C2' },
  { brand: 'JCB', model: '86Z-1' },
  { brand: 'JCB', model: '90Z-1' },
  { brand: 'JCB', model: 'Hydradig 110W' },
  { brand: 'JCB', model: 'Hydradig 17 ton (2019)' },
  { brand: 'JCB', model: 'JS115' },
  { brand: 'JCB', model: 'JS130' },
  { brand: 'JCB', model: 'JS130W' },
  { brand: 'JCB', model: 'JS131' },
  { brand: 'JCB', model: 'JS145' },
  { brand: 'JCB', model: 'JS145W' },
  { brand: 'JCB', model: 'JS150X' },
  { brand: 'JCB', model: 'JS160' },
  { brand: 'JCB', model: 'JS160W' },
  { brand: 'JCB', model: 'JS175W' },
  { brand: 'JCB', model: 'JS180' },
  { brand: 'JCB', model: 'JS190' },
  { brand: 'JCB', model: 'JS200' },
  { brand: 'JCB', model: 'JS200W' },
  { brand: 'JCB', model: 'JS210' },
  { brand: 'JCB', model: 'JS220' },
  { brand: 'JCB', model: 'JS220LR' },
  { brand: 'JCB', model: 'JS235' },
  { brand: 'JCB', model: 'JS240' },
  { brand: 'JCB', model: 'JS260' },
  { brand: 'JCB', model: 'JS260LR' },
  { brand: 'JCB', model: 'JS300' },
  { brand: 'JCB', model: 'JS330' },
  { brand: 'JCB', model: 'JS330LR' },
  { brand: 'JCB', model: 'JS370' },
  { brand: 'JCB', model: 'JZ140' },
  { brand: 'JCB', model: 'JZ140D' },
  { brand: 'JCB', model: 'JZ140LC' },
  { brand: 'JCB', model: 'JZ141' },
  { brand: 'JCB', model: 'JZ235' },
  { brand: 'JCB', model: 'JZ255' },
  { brand: 'JCB', model: 'JZ70' },
  { brand: 'JCB', model: 'Micro' },
  { brand: 'JCB', model: 'MICRO 8008' },
  { brand: 'JCB', model: 'Micro plus' },
  { brand: 'JCB', model: 'Midi CX' },
  { brand: 'Kato', model: 'HD1023' },
  { brand: 'Kato', model: 'HD513x' },
  { brand: 'Kato', model: 'HD820x' },
  { brand: 'Kato', model: 'HD823x' },
  { brand: 'Kobelco', model: 'ED160' },
  { brand: 'Kobelco', model: 'ED160BR-7' },
  { brand: 'Kobelco', model: 'SK 210' },
  { brand: 'Kobelco', model: 'SK 230' },
  { brand: 'Kobelco', model: 'SK 260 Compact' },
  { brand: 'Kobelco', model: 'SK10' },
  { brand: 'Kobelco', model: 'SK130' },
  { brand: 'Kobelco', model: 'SK130LC-11' },
  { brand: 'Kobelco', model: 'SK135' },
  { brand: 'Kobelco', model: 'SK13SR' },
  { brand: 'Kobelco', model: 'SK140' },
  { brand: 'Kobelco', model: 'SK140SRLC-7' },
  { brand: 'Kobelco', model: 'SK170LC-10' },
  { brand: 'Kobelco', model: 'SK170LC-11' },
  { brand: 'Kobelco', model: 'SK17SR-3' },
  { brand: 'Kobelco', model: 'SK17SR-6E' },
  { brand: 'Kobelco', model: 'SK18' },
  { brand: 'Kobelco', model: 'SK180' },
  { brand: 'Kobelco', model: 'SK25SR-6E' },
  { brand: 'Kobelco', model: 'SK260LC' },
  { brand: 'Kobelco', model: 'SK26SR-7' },
  { brand: 'Kobelco', model: 'SK270 SRLC-5' },
  { brand: 'Kobelco', model: 'SK27SR-5' },
  { brand: 'Kobelco', model: 'SK28SR-6E' },
  { brand: 'Kobelco', model: 'SK30' },
  { brand: 'Kobelco', model: 'SK300LC-10' },
  { brand: 'Kobelco', model: 'SK30SR-6E' },
  { brand: 'Kobelco', model: 'SK34' },
  { brand: 'Kobelco', model: 'SK35' },
  { brand: 'Kobelco', model: 'SK35SR-6E' },
  { brand: 'Kobelco', model: 'SK35SR-7' },
  { brand: 'Kobelco', model: 'SK39-7' },
  { brand: 'Kobelco', model: 'SK380XD-11' },
  { brand: 'Kobelco', model: 'SK45SRX-7' },
  { brand: 'Kobelco', model: 'SK550 Long reach' },
  { brand: 'Kobelco', model: 'SK55SRX-6' },
  { brand: 'Kobelco', model: 'SK55SRX-7' },
  { brand: 'Kobelco', model: 'SK70RS' },
  { brand: 'Kobelco', model: 'SK75SR' },
  { brand: 'Kobelco', model: 'SK75SR-7' },
  { brand: 'Kobelco', model: 'SK85CS-7' },
  { brand: 'Kobelco', model: 'SK85MSR' },
  { brand: 'Komatsu', model: 'HB215LC-2' },
  { brand: 'Komatsu', model: 'PC/PW 110' },
  { brand: 'Komatsu', model: 'PC/PW 75R' },
  { brand: 'Komatsu', model: 'PC/PW 95R' },
  { brand: 'Komatsu', model: 'PC138USLC-11' },
  { brand: 'Komatsu', model: 'PC160' },
  { brand: 'Komatsu', model: 'PC170' },
  { brand: 'Komatsu', model: 'PC190' },
  { brand: 'Komatsu', model: 'PC210' },
  { brand: 'Komatsu', model: 'PC228' },
  { brand: 'Komatsu', model: 'PC230' },
  { brand: 'Komatsu', model: 'PC26' },
  { brand: 'Komatsu', model: 'PC290LC-11' },
  { brand: 'Komatsu', model: 'PC30MR alt.1' },
  { brand: 'Komatsu', model: 'PC30MR alt.2' },
  { brand: 'Komatsu', model: 'PC360 LC-11' },
  { brand: 'Komatsu', model: 'PC360LC-10' },
  { brand: 'Komatsu', model: 'PC390 LC-11' },
  { brand: 'Komatsu', model: 'PC390HRD-11E0' },
  { brand: 'Komatsu', model: 'PC45MR-3' },
  { brand: 'Komatsu', model: 'PC490 LC11' },
  { brand: 'Komatsu', model: 'PC50' },
  { brand: 'Komatsu', model: 'PC55MR-3' },
  { brand: 'Komatsu', model: 'PC78MR' },
  { brand: 'Komatsu', model: 'PC80MR-5' },
  { brand: 'Komatsu', model: 'PC88MR' },
  { brand: 'Komatsu', model: 'PW118' },
  { brand: 'Komatsu', model: 'PW138' },
  { brand: 'Komatsu', model: 'PW148' },
  { brand: 'Komatsu', model: 'PW160' },
  { brand: 'Komatsu', model: 'PW168-11' },
  { brand: 'Komatsu', model: 'PW180' },
  { brand: 'Komatsu', model: 'PW198-11' },
  { brand: 'Komatsu', model: 'PW98MR-8' },
  { brand: 'Kubota', model: 'A33' },
  { brand: 'Kubota', model: 'K008-3' },
  { brand: 'Kubota', model: 'KX016-4' },
  { brand: 'Kubota', model: 'KX019' },
  { brand: 'Kubota', model: 'KX019-4' },
  { brand: 'Kubota', model: 'KX027-4' },
  { brand: 'Kubota', model: 'KX040' },
  { brand: 'Kubota', model: 'KX042-4' },
  { brand: 'Kubota', model: 'KX057' },
  { brand: 'Kubota', model: 'KX060-5' },
  { brand: 'Kubota', model: 'KX080' },
  { brand: 'Kubota', model: 'KX080-3' },
  { brand: 'Kubota', model: 'KX080-4' },
  { brand: 'Kubota', model: 'KX101-3' },
  { brand: 'Kubota', model: 'KX121-2' },
  { brand: 'Kubota', model: 'KX121-3' },
  { brand: 'Kubota', model: 'KX161' },
  { brand: 'Kubota', model: 'KX161-2' },
  { brand: 'Kubota', model: 'KX161-3' },
  { brand: 'Kubota', model: 'KX251' },
  { brand: 'Kubota', model: 'KX36-2' },
  { brand: 'Kubota', model: 'KX36-3' },
  { brand: 'Kubota', model: 'KX41-2' },
  { brand: 'Kubota', model: 'KX41-3' },
  { brand: 'Kubota', model: 'KX61-2' },
  { brand: 'Kubota', model: 'KX61-3' },
  { brand: 'Kubota', model: 'KX71-2' },
  { brand: 'Kubota', model: 'KX71-3 alt. 1' },
  { brand: 'Kubota', model: 'KX71-3 alt. 2' },
  { brand: 'Kubota', model: 'KX085' },
  { brand: 'Kubota', model: 'KX91-2' },
  { brand: 'Kubota', model: 'KX91-3' },
  { brand: 'Kubota', model: 'R310' },
  { brand: 'Kubota', model: 'RX-306E' },
  { brand: 'Kubota', model: 'RX-406E' },
  { brand: 'Kubota', model: 'RX-506' },
  { brand: 'Kubota', model: 'SR70' },
  { brand: 'Kubota', model: 'U-40-6e' },
  { brand: 'Kubota', model: 'U10-3' },
  { brand: 'Kubota', model: 'U145' },
  { brand: 'Kubota', model: 'U15-3' },
  { brand: 'Kubota', model: 'U17-3' },
  { brand: 'Kubota', model: 'U20-3' },
  { brand: 'Kubota', model: 'U25-3' },
  { brand: 'Kubota', model: 'U25-3a' },
  { brand: 'Kubota', model: 'U27-4' },
  { brand: 'Kubota', model: 'U30-3' },
  { brand: 'Kubota', model: 'U30-6a' },
  { brand: 'Kubota', model: 'U35-2' },
  { brand: 'Kubota', model: 'U35-3' },
  { brand: 'Kubota', model: 'U35-6' },
  { brand: 'Kubota', model: 'U35-6a' },
  { brand: 'Kubota', model: 'U45-2' },
  { brand: 'Kubota', model: 'U45-3' },
  { brand: 'Kubota', model: 'U48' },
  { brand: 'Kubota', model: 'U48-4' },
  { brand: 'Kubota', model: 'U50' },
  { brand: 'Kubota', model: 'U55' },
  { brand: 'Kubota', model: 'U55-4' },
  { brand: 'Kubota', model: 'U55-6' },
  { brand: 'Kubota', model: 'U56-5' },
  { brand: 'Kubota', model: 'UC20-3' },
  { brand: 'Kubota', model: 'UC25-3' },
  { brand: 'Liebherr', model: '934Li' },
  { brand: 'Liebherr', model: '938 G8' },
  { brand: 'Liebherr', model: 'A309' },
  { brand: 'Liebherr', model: 'A309Li' },
  { brand: 'Liebherr', model: 'A311' },
  { brand: 'Liebherr', model: 'A311Li' },
  { brand: 'Liebherr', model: 'A312Li' },
  { brand: 'Liebherr', model: 'A314Li' },
  { brand: 'Liebherr', model: 'A316LI' },
  { brand: 'Liebherr', model: 'A900B' },
  { brand: 'Liebherr', model: 'A900Bli' },
  { brand: 'Liebherr', model: 'A900C' },
  { brand: 'Liebherr', model: 'A900CLi' },
  { brand: 'Liebherr', model: 'A900Li' },
  { brand: 'Liebherr', model: 'A902' },
  { brand: 'Liebherr', model: 'A904CLi' },
  { brand: 'Liebherr', model: 'A904Li' },
  { brand: 'Liebherr', model: 'A909' },
  { brand: 'Liebherr', model: 'A911' },
  { brand: 'Liebherr', model: 'A910' },
  { brand: 'Liebherr', model: 'A910C' },
  { brand: 'Liebherr', model: 'A912' },
  { brand: 'Liebherr', model: 'A912C' },
  { brand: 'Liebherr', model: 'A913 CLi' },
  { brand: 'Liebherr', model: 'A914 C' },
  { brand: 'Liebherr', model: 'A914 CLi' },
  { brand: 'Liebherr', model: 'A914 Li' },
  { brand: 'Liebherr', model: 'A916' },
  { brand: 'Liebherr', model: 'A916 Li III-B' },
  { brand: 'Liebherr', model: 'A918 Cli III-B' },
  { brand: 'Liebherr', model: 'A918 Cli IV' },
  { brand: 'Liebherr', model: 'A918 Comp' },
  { brand: 'Liebherr', model: 'A918 Li III-B' },
  { brand: 'Liebherr', model: 'A918C' },
  { brand: 'Liebherr', model: 'A920' },
  { brand: 'Liebherr', model: 'A920 Li' },
  { brand: 'Liebherr', model: 'A922 Rail Li' },
  { brand: 'Liebherr', model: 'A924 C' },
  { brand: 'Liebherr', model: 'A924 C Plus' },
  { brand: 'Liebherr', model: 'A924 Heavy Lift' },
  { brand: 'Liebherr', model: 'A924 Li' },
  { brand: 'Liebherr', model: 'A924 Rail Li' },
  { brand: 'Liebherr', model: 'LH22' },
  { brand: 'Liebherr', model: 'LH24' },
  { brand: 'Liebherr', model: 'R313Li' },
  { brand: 'Liebherr', model: 'R317Li' },
  { brand: 'Liebherr', model: 'R906' },
  { brand: 'Liebherr', model: 'R914' },
  { brand: 'Liebherr', model: 'R914 Bli' },
  { brand: 'Liebherr', model: 'R914 Cli' },
  { brand: 'Liebherr', model: 'R914B/Cli' },
  { brand: 'Liebherr', model: 'R916' },
  { brand: 'Liebherr', model: 'R918 III-B' },
  { brand: 'Liebherr', model: 'R920 III-B' },
  { brand: 'Liebherr', model: 'R920C' },
  { brand: 'Liebherr', model: 'R922 Li' },
  { brand: 'Liebherr', model: 'R922-G8' },
  { brand: 'Liebherr', model: 'R924 compact' },
  { brand: 'Liebherr', model: 'R924 III-B Li' },
  { brand: 'Liebherr', model: 'R924B/Cli' },
  { brand: 'Liebherr', model: 'R926' },
  { brand: 'Liebherr', model: 'R926 13m Multiuser' },
  { brand: 'Liebherr', model: 'R926 Compact alt. 1' },
  { brand: 'Liebherr', model: 'R926 Compact alt. 2' },
  { brand: 'Liebherr', model: 'R928' },
  { brand: 'Liebherr', model: 'R930 G8' },
  { brand: 'Liebherr', model: 'R936' },
  { brand: 'Liebherr', model: 'R944' },
  { brand: 'Liebherr', model: 'R946' },
  { brand: 'Liebherr', model: 'R954' },
  { brand: 'Liebherr', model: 'R956' },
  { brand: 'Liebherr', model: 'R964' },
  { brand: 'Liebherr', model: 'R966' },
  { brand: 'Liebherr', model: 'R970' },
  { brand: 'Link-Belt', model: '130 X2/X3/X4' },
  { brand: 'Link-Belt', model: '130LX' },
  { brand: 'Link-Belt', model: '135 MSR' },
  { brand: 'Link-Belt', model: '135SA' },
  { brand: 'Link-Belt', model: '145 X3' },
  { brand: 'Link-Belt', model: '160 X2/X3/X4' },
  { brand: 'Link-Belt', model: '1600 Quantum' },
  { brand: 'Link-Belt', model: '160LX' },
  { brand: 'Link-Belt', model: '160X2' },
  { brand: 'Link-Belt', model: '210 X2/X3/X4' },
  { brand: 'Link-Belt', model: '210 X2/X3/X4 L/F' },
  { brand: 'Link-Belt', model: '210LX' },
  { brand: 'Link-Belt', model: '225 MSR' },
  { brand: 'Link-Belt', model: '225SA' },
  { brand: 'Link-Belt', model: '235 X3' },
  { brand: 'Link-Belt', model: '240 X2' },
  { brand: 'Link-Belt', model: '240 X2 L/F' },
  { brand: 'Link-Belt', model: '240 X2 MH' },
  { brand: 'Link-Belt', model: '240LX' },
  { brand: 'Link-Belt', model: '250 X3/X4' },
  { brand: 'Link-Belt', model: '250 X3/X4 L/F' },
  { brand: 'Link-Belt', model: '250 X3/X4 MH' },
  { brand: 'Link-Belt', model: '2650 Quantum' },
  { brand: 'Link-Belt', model: '2700 Quantum' },
  { brand: 'Link-Belt', model: '2800 Quantum' },
  { brand: 'Link-Belt', model: '290 X2' },
  { brand: 'Link-Belt', model: '290LX' },
  { brand: 'Link-Belt', model: '300 X3/X4' },
  { brand: 'Link-Belt', model: '330 LX T III' },
  { brand: 'Link-Belt', model: '330LX' },
  { brand: 'Link-Belt', model: '3400 Quantum' },
  { brand: 'Link-Belt', model: '350 X2/X3/X4' },
  { brand: 'Link-Belt', model: '3900 Quantum' },
  { brand: 'Link-Belt', model: '4300 Quantum' },
  { brand: 'Link-Belt', model: '460 LX T III' },
  { brand: 'Link-Belt', model: '460LX/X2' },
  { brand: 'Link-Belt', model: '470 X3/X4' },
  { brand: 'Link-Belt', model: '5800 Quantum' },
  { brand: 'Link-Belt', model: '700LX/X2' },
  { brand: 'Link-Belt', model: '75 MSR & X3' },
  { brand: 'Link-Belt', model: '750 X4' },
  { brand: 'Link-Belt', model: '75SA' },
  { brand: 'Link-Belt', model: '80 MSR & X3' },
  { brand: 'Link-Belt', model: '8000 Quantum' },
  { brand: 'Link-Belt', model: '8000 Quantum MASS' },
  { brand: 'Link-Belt', model: '800LX/X2' },
  { brand: 'Link-Belt', model: '80SA' },
  { brand: 'LiuGong', model: '9017F ZTS' },
  { brand: 'LiuGong', model: '9018F' },
  { brand: 'LiuGong', model: '9027F ZTS' },
  { brand: 'LiuGong', model: '9035E' },
  { brand: 'LiuGong', model: '9047F ZTS' },
  { brand: 'LiuGong', model: '9057F ZTS' },
  { brand: 'LiuGong', model: '909E CR' },
  { brand: 'LiuGong', model: '913F' },
  { brand: 'LiuGong', model: '913F CR' },
  { brand: 'LiuGong', model: '915E' },
  { brand: 'LiuGong', model: '915F' },
  { brand: 'LiuGong', model: '915F CR' },
  { brand: 'LiuGong', model: '922E' },
  { brand: 'LiuGong', model: '922F' },
  { brand: 'LiuGong', model: '922F LL' },
  { brand: 'LiuGong', model: '924F' },
  { brand: 'LiuGong', model: '925E' },
  { brand: 'LiuGong', model: '926F' },
  { brand: 'LiuGong', model: '926F LL' },
  { brand: 'LiuGong', model: '928F' },
  { brand: 'LiuGong', model: '930E' },
  { brand: 'LiuGong', model: '930F' },
  { brand: 'LiuGong', model: '933E' },
  { brand: 'LiuGong', model: '933F' },
  { brand: 'LiuGong', model: '936E' },
  { brand: 'LiuGong', model: '936E LL 20M' },
  { brand: 'LiuGong', model: '936F' },
  { brand: 'LiuGong', model: '936F LL 20M' },
  { brand: 'LiuGong', model: '939E' },
  { brand: 'LiuGong', model: '939F' },
  { brand: 'LiuGong', model: '942F' },
  { brand: 'LiuGong', model: '950E' },
  { brand: 'LiuGong', model: '952E' },
  { brand: 'LiuGong', model: '952E LL' },
  { brand: 'LiuGong', model: '995F' },
  { brand: 'Lännen', model: '8800K' },
  { brand: 'Mecalac', model: '10MCR' },
  { brand: 'Mecalac', model: '10MCR without connect' },
  { brand: 'Mecalac', model: '11MWR without connect' },
  { brand: 'Mecalac', model: '12 MTX (alt 2)' },
  { brand: 'Mecalac', model: '12MTX without connect (alt 1)' },
  { brand: 'Mecalac', model: '15MWR (alt 1)' },
  { brand: 'Mecalac', model: '15MWR (alt 2)' },
  { brand: 'Mecalac', model: '6MCR with connect' },
  { brand: 'Mecalac', model: '6MCR without connect' },
  { brand: 'Mecalac', model: '714MWe' },
  { brand: 'Mecalac', model: '7MWR' },
  { brand: 'Mecalac', model: '7MWR without connect' },
  { brand: 'Mecalac', model: '8MCR with connect' },
  { brand: 'Mecalac', model: '8MCR without connect' },
  { brand: 'Mecalac', model: '9MWR' },
  { brand: 'Mecalac', model: '9MWR without connect' },
  { brand: 'Menzi Muck', model: 'M3/M5' },
  { brand: 'Nagano/Hanix', model: 'N36' },
  { brand: 'New Holland', model: 'E12D' },
  { brand: 'New Holland', model: 'E140LCC' },
  { brand: 'New Holland', model: 'E200SR' },
  { brand: 'New Holland', model: 'E29BSR' },
  { brand: 'New Holland', model: 'E40.2SR' },
  { brand: 'New Holland', model: 'E50.2SR' },
  { brand: 'New Holland', model: 'E70' },
  { brand: 'New Holland', model: 'E75' },
  { brand: 'O&K MH City', model: '-' },
  { brand: 'Sany', model: 'SW155' },
  { brand: 'Sany', model: 'SY135C' },
  { brand: 'Sany', model: 'SY135C813K' },
  { brand: 'Sany', model: 'SY155U' },
  { brand: 'Sany', model: 'SY155W' },
  { brand: 'Sany', model: 'SY16C' },
  { brand: 'Sany', model: 'SY175W' },
  { brand: 'Sany', model: 'SY18C' },
  { brand: 'Sany', model: 'SY215C LC' },
  { brand: 'Sany', model: 'SY215C NLC' },
  { brand: 'Sany', model: 'SY265C LC' },
  { brand: 'Sany', model: 'SY26U' },
  { brand: 'Sany', model: 'SY305C LC' },
  { brand: 'Sany', model: 'SY35U' },
  { brand: 'Sany', model: 'SY365H' },
  { brand: 'Sany', model: 'SY390H' },
  { brand: 'Sany', model: 'SY500H (alt. 1)' },
  { brand: 'Sany', model: 'SY500HRD (alt. 2)' },
  { brand: 'Sany', model: 'SY50U' },
  { brand: 'Sany', model: 'SY60C' },
  { brand: 'Sany', model: 'SY75C' },
  { brand: 'Sany', model: 'SY80U' },
  { brand: 'Sunward', model: '28' },
  { brand: 'Sunward', model: '50U' },
  { brand: 'Sunward', model: 'SWE 90' },
  { brand: 'Sunward', model: 'SWE08B' },
  { brand: 'Sunward', model: 'SWE155F' },
  { brand: 'Sunward', model: 'SWE18UF' },
  { brand: 'Sunward', model: 'SWE20B' },
  { brand: 'Sunward', model: 'SWE20F' },
  { brand: 'Sunward', model: 'SWE215F' },
  { brand: 'Sunward', model: 'SWE25' },
  { brand: 'Sunward', model: 'SWE25F' },
  { brand: 'Sunward', model: 'SWE25UF' },
  { brand: 'Sunward', model: 'SWE30' },
  { brand: 'Sunward', model: 'SWE355F' },
  { brand: 'Sunward', model: 'SWE35UF' },
  { brand: 'Sunward', model: 'SWE38' },
  { brand: 'Sunward', model: 'SWE40' },
  { brand: 'Sunward', model: 'SWE40UB' },
  { brand: 'Sunward', model: 'SWE50' },
  { brand: 'Sunward', model: 'SWE60B' },
  { brand: 'Sunward', model: 'SWE60UF' },
  { brand: 'Sunward', model: 'SWE90UF' },
  { brand: 'Takeuchi', model: 'TB014' },
  { brand: 'Takeuchi', model: 'TB016' },
  { brand: 'Takeuchi', model: 'TB025' },
  { brand: 'Takeuchi', model: 'TB028' },
  { brand: 'Takeuchi', model: 'TB030' },
  { brand: 'Takeuchi', model: 'TB070' },
  { brand: 'Takeuchi', model: 'TB108' },
  { brand: 'Takeuchi', model: 'TB1140' },
  { brand: 'Takeuchi', model: 'TB125' },
  { brand: 'Takeuchi', model: 'TB135' },
  { brand: 'Takeuchi', model: 'TB138FR' },
  { brand: 'Takeuchi', model: 'TB145' },
  { brand: 'Takeuchi', model: 'TB153' },
  { brand: 'Takeuchi', model: 'TB175' },
  { brand: 'Takeuchi', model: 'TB175W' },
  { brand: 'Takeuchi', model: 'TB180FR' },
  { brand: 'Takeuchi', model: 'TB210R' },
  { brand: 'Takeuchi', model: 'TB2150' },
  { brand: 'Takeuchi', model: 'TB215R' },
  { brand: 'Takeuchi', model: 'TB216' },
  { brand: 'Takeuchi', model: 'TB219' },
  { brand: 'Takeuchi', model: 'TB228' },
  { brand: 'Takeuchi', model: 'TB230' },
  { brand: 'Takeuchi', model: 'TB235' },
  { brand: 'Takeuchi', model: 'TB240' },
  { brand: 'Takeuchi', model: 'TB250' },
  { brand: 'Takeuchi', model: 'TB260' },
  { brand: 'Takeuchi', model: 'TB280' },
  { brand: 'Takeuchi', model: 'TB280FR' },
  { brand: 'Takeuchi', model: 'TB285' },
  { brand: 'Takeuchi', model: 'TB28FR' },
  { brand: 'Takeuchi', model: 'TB290' },
  { brand: 'Takeuchi', model: 'TB295' },
  { brand: 'Takeuchi', model: 'TB295W' },
  { brand: 'Takeuchi', model: 'TB325R' },
  { brand: 'Takeuchi', model: 'TB370' },
  { brand: 'Takeuchi', model: 'TB395' },
  { brand: 'Terex', model: 'TC125' },
  { brand: 'Terex', model: 'TC25' },
  { brand: 'Terex', model: 'TC37' },
  { brand: 'Terex', model: 'TC48' },
  { brand: 'Terex', model: 'TC50' },
  { brand: 'Terex', model: 'TC60' },
  { brand: 'Terex', model: 'TC75' },
  { brand: 'Terex', model: 'TW110' },
  { brand: 'Terex', model: 'TW70' },
  { brand: 'Terex', model: 'TW75' },
  { brand: 'Terex', model: 'TW85' },
  { brand: 'Terex', model: 'TW95' },
  { brand: 'Volvo', model: 'EC120D' },
  { brand: 'Volvo', model: 'EC140B' },
  { brand: 'Volvo', model: 'EC140C' },
  { brand: 'Volvo', model: 'EC140D' },
  { brand: 'Volvo', model: 'EC140E' },
  { brand: 'Volvo', model: 'EC15C' },
  { brand: 'Volvo', model: 'EC160' },
  { brand: 'Volvo', model: 'EC160B' },
  { brand: 'Volvo', model: 'EC160C' },
  { brand: 'Volvo', model: 'EC160D' },
  { brand: 'Volvo', model: 'EC170D' },
  { brand: 'Volvo', model: 'EC17C' },
  { brand: 'Volvo', model: 'EC180B' },
  { brand: 'Volvo', model: 'EC180C' },
  { brand: 'Volvo', model: 'EC180D' },
  { brand: 'Volvo', model: 'EC18C' },
  { brand: 'Volvo', model: 'EC200E' },
  { brand: 'Volvo', model: 'EC20B/C' },
  { brand: 'Volvo', model: 'EC20C' },
  { brand: 'Volvo', model: 'EC210' },
  { brand: 'Volvo', model: 'EC210D LR' },
  { brand: 'Volvo', model: 'EC220D' },
  { brand: 'Volvo', model: 'EC220E' },
  { brand: 'Volvo', model: 'EC220E LR' },
  { brand: 'Volvo', model: 'EC235' },
  { brand: 'Volvo', model: 'EC240B' },
  { brand: 'Volvo', model: 'EC240C' },
  { brand: 'Volvo', model: 'EC25' },
  { brand: 'Volvo', model: 'ECR25' },
  { brand: 'Volvo', model: 'EC250D' },
  { brand: 'Volvo', model: 'EC250E' },
  { brand: 'Volvo', model: 'EC250E LR' },
  { brand: 'Volvo', model: 'EC260 F LR' },
  { brand: 'Volvo', model: 'EC250EL' },
  { brand: 'Volvo', model: 'EC27C' },
  { brand: 'Volvo', model: 'EC290C' },
  { brand: 'Volvo', model: 'EC30' },
  { brand: 'Volvo', model: 'ECR30' },
  { brand: 'Volvo', model: 'EC300D' },
  { brand: 'Volvo', model: 'EC300E' },
  { brand: 'Volvo', model: 'EC300E LR' },
  { brand: 'Volvo', model: 'EC300EL' },
  { brand: 'Volvo', model: 'EC350' },
  { brand: 'Volvo', model: 'EC350D' },
  { brand: 'Volvo', model: 'EC350E' },
  { brand: 'Volvo', model: 'EC350EL' },
  { brand: 'Volvo', model: 'EC35C' },
  { brand: 'Volvo', model: 'EC35D' },
  { brand: 'Volvo', model: 'EC360C HR' },
  { brand: 'Volvo', model: 'EC360D HR' },
  { brand: 'Volvo', model: 'EC380' },
  { brand: 'Volvo', model: 'EC380D' },
  { brand: 'Volvo', model: 'EC380E' },
  { brand: 'Volvo', model: 'EC380E HR' },
  { brand: 'Volvo', model: 'EC380EL' },
  { brand: 'Volvo', model: 'EC400EL' },
  { brand: 'Volvo', model: 'EC40D' },
  { brand: 'Volvo', model: 'EC460C HR' },
  { brand: 'Volvo', model: 'EC480' },
  { brand: 'Volvo', model: 'EC480D HR' },
  { brand: 'Volvo', model: 'EC480E HR' },
  { brand: 'Volvo', model: 'EC480EL' },
  { brand: 'Volvo', model: 'EC500EL' },
  { brand: 'Volvo', model: 'EC530E' },
  { brand: 'Volvo', model: 'EC550E' },
  { brand: 'Volvo', model: 'EC55B' },
  { brand: 'Volvo', model: 'EC55C' },
  { brand: 'Volvo', model: 'EC60' },
  { brand: 'Volvo', model: 'EC700B HR' },
  { brand: 'Volvo', model: 'EC700C HR' },
  { brand: 'Volvo', model: 'EC750E' },
  { brand: 'Volvo', model: 'EC750E HR' },
  { brand: 'Volvo', model: 'ECR145C' },
  { brand: 'Volvo', model: 'ECR145D' },
  { brand: 'Volvo', model: 'ECR145E' },
  { brand: 'Volvo', model: 'ECR235' },
  { brand: 'Volvo', model: 'ECR355E' },
  { brand: 'Volvo', model: 'ECR38' },
  { brand: 'Volvo', model: 'ECR48' },
  { brand: 'Volvo', model: 'ECR48PRO' },
  { brand: 'Volvo', model: 'ECR50' },
  { brand: 'Volvo', model: 'ECR58' },
  { brand: 'Volvo', model: 'ECR88' },
  { brand: 'Volvo', model: 'ECR88 G2 (Old)' },
  { brand: 'Volvo', model: 'ECR88D' },
  { brand: 'Volvo', model: 'EW140B' },
  { brand: 'Volvo', model: 'EW140C' },
  { brand: 'Volvo', model: 'EW140D' },
  { brand: 'Volvo', model: 'EW160' },
  { brand: 'Volvo', model: 'EW160B' },
  { brand: 'Volvo', model: 'EW160C' },
  { brand: 'Volvo', model: 'EW160D' },
  { brand: 'Volvo', model: 'EW160E' },
  { brand: 'Volvo', model: 'EW180' },
  { brand: 'Volvo', model: 'EW205D' },
  { brand: 'Volvo', model: 'EW205E Korean Machine' },
  { brand: 'Volvo', model: 'EW210' },
  { brand: 'Volvo', model: 'EW220D' },
  { brand: 'Volvo', model: 'EW230' },
  { brand: 'Volvo', model: 'EW240EMH' },
  { brand: 'Volvo', model: 'EW60' },
  { brand: 'Volvo', model: 'EW60 Korea' },
  { brand: 'Volvo', model: 'EWR130' },
  { brand: 'Volvo', model: 'EWR150' },
  { brand: 'Volvo', model: 'EWR170E' },
  { brand: 'Wacker Neuson', model: '1903' },
  { brand: 'Wacker Neuson', model: '2203' },
  { brand: 'Wacker Neuson', model: '2404' },
  { brand: 'Wacker Neuson', model: '2503' },
  { brand: 'Wacker Neuson', model: '28' },
  { brand: 'Wacker Neuson', model: '28z03' },
  { brand: 'Wacker Neuson', model: '38z3' },
  { brand: 'Wacker Neuson', model: '50Z3' },
  { brand: 'Wacker Neuson', model: '6003' },
  { brand: 'Wacker Neuson', model: '6503' },
  { brand: 'Wacker Neuson', model: '75z3' },
  { brand: 'Wacker Neuson', model: '8002' },
  { brand: 'Wacker Neuson', model: '8003' },
  { brand: 'Wacker Neuson', model: '9503' },
  { brand: 'Wacker Neuson', model: 'E150B' },
  { brand: 'Wacker Neuson', model: 'ET145' },
  { brand: 'Wacker Neuson', model: 'ET16' },
  { brand: 'Wacker Neuson', model: 'ET18' },
  { brand: 'Wacker Neuson', model: 'ET20' },
  { brand: 'Wacker Neuson', model: 'ET24' },
  { brand: 'Wacker Neuson', model: 'ET42' },
  { brand: 'Wacker Neuson', model: 'ET65' },
  { brand: 'Wacker Neuson', model: 'ET90' },
  { brand: 'Wacker Neuson', model: 'EW100 (alt. 1)' },
  { brand: 'Wacker Neuson', model: 'EW100 (alt. 2)' },
  { brand: 'Wacker Neuson', model: 'EW65' },
  { brand: 'Wacker Neuson', model: 'EX17' },
  { brand: 'Wacker Neuson', model: 'EZ17' },
  { brand: 'Wacker Neuson', model: 'EZ50' },
  { brand: 'XCMG', model: 'XE150E' },
  { brand: 'XCMG', model: 'XE155ECR' },
  { brand: 'XCMG', model: 'XE155WECR' },
  { brand: 'XCMG', model: 'XE15E' },
  { brand: 'XCMG', model: 'XE160W' },
  { brand: 'XCMG', model: 'XE18E' },
  { brand: 'XCMG', model: 'XE210E' },
  { brand: 'XCMG', model: 'XE220E/EN' },
  { brand: 'XCMG', model: 'XE250E' },
  { brand: 'XCMG', model: 'XE260E/EN' },
  { brand: 'XCMG', model: 'XE27E' },
  { brand: 'XCMG', model: 'XE300E/EN' },
  { brand: 'XCMG', model: 'XE35E' },
  { brand: 'XCMG', model: 'XE360E' },
  { brand: 'XCMG', model: 'XE380E/EN' },
  { brand: 'XCMG', model: 'XE490E' },
  { brand: 'XCMG', model: 'XE55E' },
  { brand: 'XCMG', model: 'XE80E' },
  { brand: 'XGMA', model: '8075W' },
  { brand: 'XGMA', model: '8085W' },
  { brand: 'XGMA', model: '8095W' },
  { brand: 'XGMA', model: '8105W' },
  { brand: 'Yanmar', model: 'B110W' },
  { brand: 'Yanmar', model: 'B19-2' },
  { brand: 'Yanmar', model: 'B75W' },
  { brand: 'Yanmar', model: 'B95W' },
  { brand: 'Yanmar', model: 'Sigma7' },
  { brand: 'Yanmar', model: 'SV08' },
  { brand: 'Yanmar', model: 'SV100' },
  { brand: 'Yanmar', model: 'SV100-1' },
  { brand: 'Yanmar', model: 'SV120' },
  { brand: 'Yanmar', model: 'SV15/17' },
  { brand: 'Yanmar', model: 'SV16/18' },
  { brand: 'Yanmar', model: 'SV19' },
  { brand: 'Yanmar', model: 'SV20' },
  { brand: 'Yanmar', model: 'SV22' },
  { brand: 'Yanmar', model: 'SV26' },
  { brand: 'Yanmar', model: 'SV40' },
  { brand: 'Yanmar', model: 'SV60' },
  { brand: 'Yanmar', model: 'SV85' },
  { brand: 'Yanmar', model: 'SV86-7' },
  { brand: 'Yanmar', model: 'VIO10-12' },
  { brand: 'Yanmar', model: 'VIO15' },
  { brand: 'Yanmar', model: 'VIO17' },
  { brand: 'Yanmar', model: 'VIO25' },
  { brand: 'Yanmar', model: 'VIO26-6' },
  { brand: 'Yanmar', model: 'VIO27-6' },
  { brand: 'Yanmar', model: 'VIO30' },
  { brand: 'Yanmar', model: 'VIO33' },
  { brand: 'Yanmar', model: 'VIO35' },
  { brand: 'Yanmar', model: 'VIO38' },
  { brand: 'Yanmar', model: 'VIO40' },
  { brand: 'Yanmar', model: 'VIO40V' },
  { brand: 'Yanmar', model: 'VIO45' },
  { brand: 'Yanmar', model: 'VIO45G' },
  { brand: 'Yanmar', model: 'VIO50' },
  { brand: 'Yanmar', model: 'VIO50U' },
  { brand: 'Yanmar', model: 'VIO55' },
  { brand: 'Yanmar', model: 'VIO55G' },
  { brand: 'Yanmar', model: 'VIO57U' },
  { brand: 'Yanmar', model: 'VIO75' },
  { brand: 'Yanmar', model: 'VIO80' },
  { brand: 'Zoomlion', model: 'ZE60-10' },
];

const BRAND_LOGO_MAP: Record<string, string> = {
  'Airman': 'Airman_logo.png',
  'Atlas': 'Atlas_logo.png',
  'Bobcat': 'Bobcat_logo.png',
  'Case': 'Case_logo2.png',
  'CAT': 'Cat_logo.png',
  'Doosan': 'Doosan_logo.png',
  'Hidromek': 'Hidromek_logo.png',
  'Hitachi': 'Hitachi_logo.png',
  'Hyundai': 'Hyundai_logo.png',
  'JCB': 'JCB_logo.png',
  'Kobelco': 'Kobelco_logo.png',
  'Komatsu': 'Komatsu_logo.png',
  'Kubota': 'Kubota_logo.png',
  'Liebherr': 'Liebherr_logo.png',
  'Link-Belt': 'Link-Belt_Logo.png',
  'Mecalac': 'Mecalac_logo.png',
  'Sany': 'sany_logo.png',
  'Sunward': 'Sunward_logo.png',
  'Takeuchi': 'Takeuchi_logo.png',
  'Terex': 'Terex_logo.png',
  'Volvo': 'Volvo_logo.png',
  'Wacker Neuson': 'wacker_neuson_logo.png',
  'XCMG': 'XCMG_logo.png',
  'Yanmar': 'Yanmar_logo.png',
};
